apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unoplat-service-mesh-certs
spec:
  secretName: unoplat-service-mesh-certs
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: unoplat-service-mesh-issuer
    kind: ClusterIssuer
  commonName: "identity.linkerd.cluster.local"
  isCA: false